export const restaurant_list = [
  {
    id: 0,
    restaurant_name: "Ovi's Places",
    description:
      "Informal counter-serve eatery serving light bites like sandwiches & salads, plus smoothies.",
    google_maps_url: "https://maps.app.goo.gl/onZLNEtPUiM9LU7R6",
    price_tag: "$",
    dates: [
      "Monday 8 AM-9 PM",
      "Tuesday 8 AM-9 PM",
      "Wednesday 8 AM-9 PM",
      "Thursday 8 AM-9 PM",
      "Friday 8 AM-9 PM",
      "Saturday 9 AM-8 PM",
      "Sunday 10 AM-7 PM",
    ],
    website: "http://ovisplaceny.com/",
    images_url: [
      "https://i.ibb.co/WDpC5n0/jsc8u2vznstbe3gdcygu.jpg",
      "https://i.ibb.co/bz2mbgf/images.jpg",
    ],
    tags: [
      "Dine-In",
      "Takeout",
      "Vegetarian",
      "Healthy",
      "Hot Food",
      "Drinks",
      "Vegetarian",
    ],
    lat: 40.63207152331077,
    lon: -73.94788045892257,
    distance_miles: 0.2,
    distance_time: "4 min Walking",
  },
  {
    id: 1,
    restaurant_name: "Spoons",
    description:
      "Kosher Restaurant with amazing food and a lot of love on all we do!",
    google_maps_url: "https://maps.app.goo.gl/dTuG2LHHyERpbHLm8",
    price_tag: "$$",
    dates: [
      "Monday, 8:30 AM–10 PM",
      "Tuesday, 8:30 AM–10 PM",
      "Wednesday, 8:30 AM–10 PM",
      "Thursday, 8:30 AM–10 PM",
      "Friday, 8:30 AM–2 PM",
      "Saturday, Closed",
      "Sunday, 8:30 AM–10 PM",
    ],
    website: "https://www.cafespoons.com/",
    images_url: [
      "https://koshercactus.com/wp-content/uploads/2021/07/WhatsApp-Image-2021-07-19-at-12.24.33-PM-1024x989.jpeg",
      "https://whereyoueat.com/r_gallery_images/rgallery-20548/0001-BG.jpg",
    ],
    tags: ["Kosher", "Dine-In", "Delivery", "Takeout"],
    lat: 40.627193892748586,
    lon: -73.94711604851716,
    distance_miles: 0.5,
    distance_time: "11 min Walking",
  },
  {
    id: 2,
    restaurant_name: "Buona Journata Halal Food Truck",
    description:
      "Halal Food Cart located in Brooklyn College more specifically at Bedford Ave before crossing to other side of campus",
    google_maps_url: "https://maps.app.goo.gl/YStUSHrCSU45D4T46",
    price_tag: "$",
    dates: [
      "Monday, 6:30 AM–8:30 PM",
      "Tuesday, 6:30 AM–8:30 PM",
      "Wednesday, 6:30 AM–8:30 PM",
      "Thursday, 6:30 AM–8:30 PM",
      "Friday, 6:30 AM–8:30 PM",
      "Saturday, Closed",
      "Sunday, Closed",
    ],
    website: "#",
    images_url: [
      "https://10619-2.s.cdn12.com/rests/original/106_475488155.jpg",
      "https://s3-media0.fl.yelpcdn.com/bphoto/bqMxv3xR9UN6mhPsdfIpfA/300s.jpg",
    ],
    tags: ["Halal", "Dine-In", "Takeout"],
    lat: 40.63166009383946,
    lon: -73.95246635131838,
    distance_miles: 1,
    distance_time: "1 min Walking",
  },
  {
    id: 3,
    restaurant_name: "Starving Vegan",
    description:
      "Real and Delicious Vegan Food, we have many healthy options and comfort food",
    google_maps_url: "https://maps.app.goo.gl/5Mtb15GKZxHhQfqWA",
    price_tag: "$$",
    dates: [
      "Monday, Closed",
      "Tuesday, 11:30 AM–10 PM",
      "Wednesday, 11:30 AM–10 PM",
      "Thursday, 11:30 AM–10 PM",
      "Friday, 11:30 AM–10 PM",
      "Saturday, 11:30 AM–10 PM",
      "Sunday, 11:30 AM–10 PM",
    ],
    website: "http://www.starvingvegans.com/",
    images_url: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQypQClA92FrjG9-tLcM22rOH3bJz3LuP5deMYbptcvQw&s",
      "https://img.cdn4dd.com/cdn-cgi/image/fit=cover,width=600,height=400,format=auto,quality=80/https://doordash-static.s3.amazonaws.com/media/store/header/cdc0e90d-93eb-4236-87b4-f1af727f1872.png",
    ],
    tags: [
      "Vegan",
      "Dine-In",
      "Curbside Pickup",
      "Delivery",
      "Takeout",
      "Healthy",
    ],
    lat: 40.62545345479856,
    lon: -73.9378548410448,
    distance_miles: 0.9,
    distance_time: "15 min Bus B41",
  },
  {
    id: 4,
    restaurant_name: "Just Salad",
    description:
      "Customized salads, wraps & smoothies are the specialties of this counter-service chain.",
    google_maps_url: "https://maps.app.goo.gl/QPNtsxDWKBzNhvoV9",
    price_tag: "$$",
    dates: [
      "Monday, 10:30 AM–9 PM",
      "Tuesday, 10:30 AM–9 PM",
      "Wednesday, 10:30 AM–9 PM",
      "Thursday, 10:30 AM–9 PM",
      "Friday, 10:30 AM–9 PM",
      "Saturday, 11 AM–9 PM",
      "Sunday, 11 AM–9 PM",
    ],
    website: "http://www.justsalad.com/",
    images_url: [
      "https://img.cdn4dd.com/cdn-cgi/image/fit=cover,width=600,height=400,format=auto,quality=80/https://doordash-static.s3.amazonaws.com/media/store/header/ece4fec2-8726-4f9e-a019-b6fb7a9fc5da.jpg",
      "https://media-cdn.tripadvisor.com/media/photo-s/21/66/75/b6/just-salad-logo.jpg",
    ],
    tags: [
      "Vegetarian",
      "Dine-In",
      "Delivery",
      "Outdoor",
      "Takeout",
      "Healthy",
    ],
    lat: 40.67139670203225,
    lon: -73.979521050523,
    distance_miles: 0,
    distance_time: "31 min Train 2",
  },
  {
    id: 5,
    restaurant_name: "Lotus Vegetarian",
    description: "Lotus Vegetarian is the best vegetarian food in Brooklyn",
    google_maps_url: "https://maps.app.goo.gl/kR54raSWs33B3noFA",
    price_tag: "$$",
    dates: [
      "Monday, 11:30 AM–10:30 PM",
      "Tuesday, 11:30 AM–10:30 PM",
      "Wednesday, 11:30 AM–10:30 PM",
      "Thursday, 11:30 AM–10:30 PM",
      "Friday, 11:30 AM–11:30 PM",
      "Saturday, 11:30 AM–11:30 PM",
      "Sunday, 12–10:30 PM",
    ],
    website: "https://www.lotusvegetarianny.com/#/",
    images_url: [
      "https://d1ralsognjng37.cloudfront.net/6e102aa8-6c34-4f5b-9e94-ae64a1d76224",
      "https://img.cdn4dd.com/cdn-cgi/image/fit=contain,width=1200,height=672,format=auto/https://doordash-static.s3.amazonaws.com/media/restaurant/cover/Lotus_Vegetarian_Brooklyn.png",
    ],
    tags: [
      "Vegetarian",
      "Dine-In",
      "Delivery",
      "Outdoor",
      "Takeout",
      "Healthy",
    ],
    lat: 40.65131031144837,
    lon: -73.95747365726697,
    distance_miles: 1.5,
    distance_time: "18 min Bus: B41",
  },
  {
    id: 6,
    restaurant_name: "Ital Fusion",
    description:
      "Vegetarian Food and many other options for pescatarian as well",
    google_maps_url: "https://maps.app.goo.gl/RNtDap1nE8ogyR2s9",
    price_tag: "$$",
    dates: [
      "Monday, 6 AM–10 PM",
      "Tuesday, 6 AM–10 PM",
      "Wednesday, 6 AM–10 PM",
      "Thursday, 6 AM–10 PM",
      "Friday, 6 AM–10 PM",
      "Saturday, 6 AM–10 PM",
      "Sunday, 6 AM–9 PM",
    ],
    website: "https://www.facebook.com/ItalFusion",
    images_url: [
      "https://s3-media0.fl.yelpcdn.com/bphoto/QUbdUj_E7cFA2uE1HINtcA/348s.jpg",
      "https://images.happycow.net/venues/1024/12/63/hcmp126397_1717549.jpeg",
    ],
    tags: [
      "Vegetarian",
      "Pescatarian",
      "Dine-In",
      "Delivery",
      "Outdoor",
      "Takeout",
      "Healthy",
      "Gluten-Free",
    ],
    lat: 0,
    lon: 0,
    distance_miles: 0,
    distance_time: "4 min Walking",
  },
  {
    id: 7,
    restaurant_name: "Buzz's World Organic Seafood LLC",
    description:
      "Best Organic Seafood in Brooklyn, roasted fish, fried fish, shrimps, you name it we got it!",
    google_maps_url: "https://maps.app.goo.gl/5Pyr8vGzH17XnMod6",
    price_tag: "$$",
    dates: [
      "Monday, 5:30 PM–12 AM",
      "Tuesday, 5:30 PM–12 AM",
      "Wednesday, 5:30 PM–12 AM",
      "Thursday, 5:30 PM–12 AM",
      "Friday, 5:30 PM–12 AM",
      "Saturday, 12 PM–12 AM",
      "Sunday, 12 PM–12 AM",
    ],
    website: "#",
    images_url: [
      "https://media-cdn.grubhub.com/image/upload/d_search:browse-images:default.jpg/w_300,q_100,fl_lossy,dpr_2.0,c_fit,f_auto,h_300/sg1hqoz7t239xbmerjrn",
      "https://s3-media0.fl.yelpcdn.com/bphoto/F-MCUF6Dz1amzt4sAlcuVg/348s.jpg",
    ],
    tags: [
      "Pescatarian",
      "SeaFood",
      "Outdoor Seating",
      "Delivery",
      "Dine-In",
      "Takeout",
    ],
    lat: 40.63442150489976,
    lon: -73.95015135695724,
    distance_miles: 0.2,
    distance_time: "6 min Walking",
  },
  {
    id: 8,
    restaurant_name: "Napoli Pizza",
    description:
      "Stalwart neighborhood counter serve offering large pies & slices in a simple venue.",
    google_maps_url: "https://maps.app.goo.gl/zoVsFqvsgQkHPtv99",
    price_tag: "$",
    dates: [
      "Monday, 11 AM–10 PM",
      "Tuesday, 11 AM–10 PM",
      "Wednesday, 11 AM–10 PM",
      "Thursday, 11 AM–10 PM",
      "Friday, 11 AM–10 PM",
      "Saturday, 11 AM–10 PM",
      "Sunday, 11 AM–9 PM",
    ],
    website: "https://www.napolimenu.com/",
    images_url: [
      "https://lh3.googleusercontent.com/proxy/3ofo8F430p2E7ALb1o04D1mTMrojyYxY_XbhUtltkAV312Bg9o7sYGFKHaUCLTqgS4B7U3q7uvKpWz4bEgKper9kaA",
      "https://s3-media0.fl.yelpcdn.com/bphoto/ncAn_FCjH6-tF5GjZr4ltA/258s.jpg",
    ],
    tags: [
      "Glutten-Free",
      "Pizza",
      "Italina Cousine",
      "Dine-In",
      "Takeout",
      "Delivery",
    ],
    lat: 40.629580289269164,
    lon: -73.94752342309471,
    distance_miles: 0.4,
    distance_time: "8 min Walking",
  },
  {
    id: 9,
    restaurant_name: "",
    description: "",
    google_maps_url: "",
    price_tag: "",
    dates: ["", "", "", "", "", "", ""],
    website: "",
    images_url: ["", ""],
    tags: [""],
    lat: 0,
    lon: 0,
    distance_miles: 0,
    distance_time: "4 min Walking",
  },
  {
    id: 10,
    restaurant_name: "",
    description: "",
    google_maps_url: "",
    price_tag: "",
    dates: ["", "", "", "", "", "", ""],
    website: "",
    images_url: ["", ""],
    tags: [""],
    lat: 0,
    lon: 0,
    distance_miles: 0,
    distance_time: "4 min Walking",
  },
  {
    id: 11,
    restaurant_name: "",
    description: "",
    google_maps_url: "",
    price_tag: "",
    dates: ["", "", "", "", "", "", ""],
    website: "",
    images_url: ["", ""],
    tags: [""],
    lat: 0,
    lon: 0,
    distance_miles: 0,
    distance_time: "4 min Walking",
  },
  {
    id: 12,
    restaurant_name: "",
    description: "",
    google_maps_url: "",
    price_tag: "",
    dates: ["", "", "", "", "", "", ""],
    website: "",
    images_url: ["", ""],
    tags: [""],
    lat: 0,
    lon: 0,
    distance_miles: 0,
    distance_time: "4 min Walking",
  },
  {
    id: 13,
    restaurant_name: "",
    description: "",
    google_maps_url: "",
    price_tag: "",
    dates: ["", "", "", "", "", "", ""],
    website: "",
    images_url: ["", ""],
    tags: [""],
    lat: 0,
    lon: 0,
    distance_miles: 0,
    distance_time: "4 min Walking",
  },
  {
    id: 14,
    restaurant_name: "",
    description: "",
    google_maps_url: "",
    price_tag: "",
    dates: ["", "", "", "", "", "", ""],
    website: "",
    images_url: ["", ""],
    tags: [""],
    lat: 0,
    lon: 0,
    distance_miles: 0,
    distance_time: "4 min Walking",
  },
  {
    id: 15,
    restaurant_name: "",
    description: "",
    google_maps_url: "",
    price_tag: "",
    dates: ["", "", "", "", "", "", ""],
    website: "",
    images_url: ["", ""],
    tags: [""],
    lat: 0,
    lon: 0,
    distance_miles: 0,
    distance_time: "4 min Walking",
  },
  {
    id: 16,
    restaurant_name: "",
    description: "",
    google_maps_url: "",
    price_tag: "",
    dates: ["", "", "", "", "", "", ""],
    website: "",
    images_url: ["", ""],
    tags: [""],
    lat: 0,
    lon: 0,
    distance_miles: 0,
    distance_time: "4 min Walking",
  },
  {
    id: 17,
    restaurant_name: "",
    description: "",
    google_maps_url: "",
    price_tag: "",
    dates: ["", "", "", "", "", "", ""],
    website: "",
    images_url: ["", ""],
    tags: [""],
    lat: 0,
    lon: 0,
    distance_miles: 0,
    distance_time: "4 min Walking",
  },
];
